[build]
rustflags = []

[target.x86_64-pc-windows-msvc]
rustflags = []

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-linux-android]
rustflags = ["-C", "target-cpu=generic", "-C", "target-feature=+neon,+aes"]
